use serde::Serialize;

pub const LOGIN_TITLE: &str = "Log In";
pub const LOGIN_URL: &str = "/login";
pub const LOGOUT_URL: &str = "/logout";
pub const REGISTER_TITLE: &str = "Register";
pub const REGISTER_URL: &str = "/register";
pub const HOME_URL: &str = "/home";
pub const HOME_TEMPLATE: &str = "home.html";
pub const LOG_REG_TEMPLATE: &str = "logReg.html";
pub const HOME_TITLE: &str = "Home";
pub const HOUSE_TITLE: &str = "House";
pub const HOUSE_URL: &str = "/house";
pub const TITLE: &str = "title";
pub const POST: &str = "POST";
pub const REGISTER: &str = "Register";
pub const INDEX_URL: &str = "/";
pub const DETAILS_URL: &str = "/details";
pub const GAME_URL: &str = "/game";
pub const SKILLS_URL: &str = "/skills";
pub const LINKS_URL: &str = "/links";
pub const QUOTES_URL: &str = "/quotes";
pub const PTABLE_URL: &str = "/ptable";

pub const CARD_ONE: [(&str, &str); 5] = [( "url", "https://res.cloudinary.com/dxrtzusla/video/upload/v1644590054/Screen_Recording_2022-02-11_at_8.28.54_AM_rrryoh.mov"),
( "ftitle", "Messenger App"),
( "contributions", "Implemented styles for the login / registration page, fixed some message rendering issues due to immutability not being enforced and added image upload functionality."),
( "takeaways", "Better understanding of React, Redux, Material UI, Axios, Express, Node.js, concurrent requests with JavaScript and what's expected in a collaborative team environment."),
("index", "0")];

pub const CARD_TWO: [(&str, &str); 5] = [( "url", "https://res.cloudinary.com/dxrtzusla/video/upload/v1644590653/Screen_Recording_2022-02-11_at_8.40.42_AM_pf4dye.mov"),
( "ftitle", "Tic-Tac-Toe"),
( "contributions", "I created a simple, unstyled tic-tac-toe app using pure HTML, CSS and JavaScript. Then I recreated the app in React and deployed it to GitHub Pages."),
( "takeaways", "Better understanding of the core JavaScript principles that React uses under the hood. How to deploy a React app to GH-Pages and how to incorporate routing in a SPA in GH-Pages (a feature that was not implemented on this tic-tac-toe app)."),
("index", "0")];

pub const CARD_THREE: [(&str, &str); 5] = [( "url", "https://res.cloudinary.com/dxrtzusla/video/upload/v1644595149/Screen_Recording_2022-02-11_at_9.54.43_AM_yyivri.mov"),
( "ftitle", "Simple API"),
( "contributions", "A backend assessment for Hatchways."),
( "takeaways", "Learned a lot about Python & backend development in this and other API projects, such as caching, multithreading, generator functions, creating/using decorators, class methods, using tools such as Postman, cURL, python requests library to interact with APIs, document databases, etc."),
("index", "0")];

pub const SKILLS: [&str; 27] = [
    "Python",
    "JavaScript",
    "React",
    "Redux",
    "Django",
    "NodeJS",
    "Flask",
    "Fastify",
    "Restful APIs",
    "HTML5",
    "CSS3",
    "Bootstrap",
    "Material UI",
    "jQuery UI",
    "VsCode",
    "VIM",
    "Bash/ZSH",
    "Git",
    "PIP / NPM web scraping libraries",
    "MTV/MVC Development Pattern",
    "SQL - NoSQL, MySQL, PostgreSQL, MSSQL",
    "ORM's",
    "AWS",
    "JSON / XML",
    "jQuery",
    "Mac / Linux",
    "SASS / LESS",
];

pub const LINKS_ONE: [(&str, &str); 2] = [
    (
        "href",
        "https://www.linkedin.com/in/alejandro-yanez-995552220/",
    ),
    ("text", "LinkedIn"),
];

pub const LINKS_TWO: [(&str, &str); 2] = [
    ("href", "https://github.com/since9teen94"),
    ("text", "GitHub"),
];

#[derive(Serialize)]
pub struct Element<'a> {
    atomic_number: &'a str,
    symbol: &'a str,
    name: &'a str,
    atomic_mass: &'a str,
    electronic_configuration: &'a str,
    electronegativity: &'a str,
    atomic_radius: &'a str,
    ion_radius: &'a str,
    van_der_waals_radius: &'a str,
    ionization_energy: &'a str,
    electron_affinity: &'a str,
    oxidation_states: &'a str,
    standard_state: &'a str,
    bonding_type: &'a str,
    melting_point: &'a str,
    boiling_point: &'a str,
    density: &'a str,
    group_block: &'a str,
    year_discovered: &'a str,
    block: &'a str,
    cpk_hex_color: &'a str,
    period: &'a str,
    group: &'a str,
}

pub const ELEMENTS: [Element; 118] = [
    Element {
        atomic_number: "1",
        symbol: "H",
        name: "Hydrogen",
        atomic_mass: "1.00794(4)",
        electronic_configuration: "1s1",
        electronegativity: "2.2",
        atomic_radius: "37",
        ion_radius: "unknown",
        van_der_waals_radius: "120",
        ionization_energy: "1312",
        electron_affinity: "-73",
        oxidation_states: "-1, 1",
        standard_state: "gas",
        bonding_type: "diatomic",
        melting_point: "14",
        boiling_point: "20",
        density: "8.99e-5",
        group_block: "nonmetal",
        year_discovered: "1766",
        block: "s",
        cpk_hex_color: "FFFFFF",
        period: "1",
        group: "1",
    },
    Element {
        atomic_number: "2",
        symbol: "He",
        name: "Helium",
        atomic_mass: "4.002602(2)",
        electronic_configuration: "1s2",
        electronegativity: "unknown",
        atomic_radius: "32",
        ion_radius: "unknown",
        van_der_waals_radius: "140",
        ionization_energy: "2372",
        electron_affinity: "0",
        oxidation_states: "unknown",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "unknown",
        boiling_point: "4",
        density: "0.0001785",
        group_block: "noble gas",
        year_discovered: "1868",
        block: "p",
        cpk_hex_color: "D9FFFF",
        period: "1",
        group: "18",
    },
    Element {
        atomic_number: "3",
        symbol: "Li",
        name: "Lithium",
        atomic_mass: "6.941(2)",
        electronic_configuration: "[He] 2s1",
        electronegativity: "0.98",
        atomic_radius: "134",
        ion_radius: "76 (+1)",
        van_der_waals_radius: "182",
        ionization_energy: "520",
        electron_affinity: "-60",
        oxidation_states: "1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "454",
        boiling_point: "1615",
        density: "0.535",
        group_block: "alkali metal",
        year_discovered: "1817",
        block: "s",
        cpk_hex_color: "CC80FF",
        period: "2",
        group: "1",
    },
    Element {
        atomic_number: "4",
        symbol: "Be",
        name: "Beryllium",
        atomic_mass: "9.012182(3)",
        electronic_configuration: "[He] 2s2",
        electronegativity: "1.57",
        atomic_radius: "90",
        ion_radius: "45 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "900",
        electron_affinity: "0",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1560",
        boiling_point: "2743",
        density: "1.848",
        group_block: "alkaline earth metal",
        year_discovered: "1798",
        block: "s",
        cpk_hex_color: "C2FF00",
        period: "2",
        group: "2",
    },
    Element {
        atomic_number: "5",
        symbol: "B",
        name: "Boron",
        atomic_mass: "10.811(7)",
        electronic_configuration: "[He] 2s2 2p1",
        electronegativity: "2.04",
        atomic_radius: "82",
        ion_radius: "27 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "801",
        electron_affinity: "-27",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "2348",
        boiling_point: "4273",
        density: "2.46",
        group_block: "metalloid",
        year_discovered: "1807",
        block: "p",
        cpk_hex_color: "FFB5B5",
        period: "1",
        group: "13",
    },
    Element {
        atomic_number: "6",
        symbol: "C",
        name: "Carbon",
        atomic_mass: "12.0107(8)",
        electronic_configuration: "[He] 2s2 2p2",
        electronegativity: "2.55",
        atomic_radius: "77",
        ion_radius: "16 (+4)",
        van_der_waals_radius: "170",
        ionization_energy: "1087",
        electron_affinity: "-154",
        oxidation_states: "-4, -3, -2, -1, 1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "3823",
        boiling_point: "4300",
        density: "2.26",
        group_block: "nonmetal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "909090",
        period: "2",
        group: "14",
    },
    Element {
        atomic_number: "7",
        symbol: "N",
        name: "Nitrogen",
        atomic_mass: "14.0067(2)",
        electronic_configuration: "[He] 2s2 2p3",
        electronegativity: "3.04",
        atomic_radius: "75",
        ion_radius: "146 (-3)",
        van_der_waals_radius: "155",
        ionization_energy: "1402",
        electron_affinity: "-7",
        oxidation_states: "-3, -2, -1, 1, 2, 3, 4, 5",
        standard_state: "gas",
        bonding_type: "diatomic",
        melting_point: "63",
        boiling_point: "77",
        density: "0.001251",
        group_block: "nonmetal",
        year_discovered: "1772",
        block: "p",
        cpk_hex_color: "3050F8",
        period: "2",
        group: "15",
    },
    Element {
        atomic_number: "8",
        symbol: "O",
        name: "Oxygen",
        atomic_mass: "15.9994(3)",
        electronic_configuration: "[He] 2s2 2p4",
        electronegativity: "3.44",
        atomic_radius: "73",
        ion_radius: "140 (-2)",
        van_der_waals_radius: "152",
        ionization_energy: "1314",
        electron_affinity: "-141",
        oxidation_states: "-2, -1, 1, 2",
        standard_state: "gas",
        bonding_type: "diatomic",
        melting_point: "55",
        boiling_point: "90",
        density: "0.001429",
        group_block: "nonmetal",
        year_discovered: "1774",
        block: "p",
        cpk_hex_color: "FF0D0D",
        period: "2",
        group: "16",
    },
    Element {
        atomic_number: "9",
        symbol: "F",
        name: "Fluorine",
        atomic_mass: "18.9984032(5)",
        electronic_configuration: "[He] 2s2 2p5",
        electronegativity: "3.98",
        atomic_radius: "71",
        ion_radius: "133 (-1)",
        van_der_waals_radius: "147",
        ionization_energy: "1681",
        electron_affinity: "-328",
        oxidation_states: "-1",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "54",
        boiling_point: "85",
        density: "0.001696",
        group_block: "halogen",
        year_discovered: "1670",
        block: "p",
        cpk_hex_color: "9eaf51",
        period: "2",
        group: "17",
    },
    Element {
        atomic_number: "10",
        symbol: "Ne",
        name: "Neon",
        atomic_mass: "20.1797(6)",
        electronic_configuration: "[He] 2s2 2p6",
        electronegativity: "unknown",
        atomic_radius: "69",
        ion_radius: "unknown",
        van_der_waals_radius: "154",
        ionization_energy: "2081",
        electron_affinity: "0",
        oxidation_states: "unknown",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "25",
        boiling_point: "27",
        density: "0.0009",
        group_block: "noble gas",
        year_discovered: "1898",
        block: "p",
        cpk_hex_color: "B3E3F5",
        period: "2",
        group: "18",
    },
    Element {
        atomic_number: "11",
        symbol: "Na",
        name: "Sodium",
        atomic_mass: "22.98976928(2)",
        electronic_configuration: "[Ne] 3s1",
        electronegativity: "0.93",
        atomic_radius: "154",
        ion_radius: "102 (+1)",
        van_der_waals_radius: "227",
        ionization_energy: "496",
        electron_affinity: "-53",
        oxidation_states: "-1, 1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "371",
        boiling_point: "1156",
        density: "0.968",
        group_block: "alkali metal",
        year_discovered: "1807",
        block: "s",
        cpk_hex_color: "AB5CF2",
        period: "3",
        group: "1",
    },
    Element {
        atomic_number: "12",
        symbol: "Mg",
        name: "Magnesium",
        atomic_mass: "24.3050(6)",
        electronic_configuration: "[Ne] 3s2",
        electronegativity: "1.31",
        atomic_radius: "130",
        ion_radius: "72 (+2)",
        van_der_waals_radius: "173",
        ionization_energy: "738",
        electron_affinity: "0",
        oxidation_states: "1, 2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "923",
        boiling_point: "1363",
        density: "1.738",
        group_block: "alkaline earth metal",
        year_discovered: "1808",
        block: "s",
        cpk_hex_color: "8AFF00",
        period: "3",
        group: "2",
    },
    Element {
        atomic_number: "13",
        symbol: "Al",
        name: "Aluminum",
        atomic_mass: "26.9815386(8)",
        electronic_configuration: "[Ne] 3s2 3p1",
        electronegativity: "1.61",
        atomic_radius: "118",
        ion_radius: "53.5 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "578",
        electron_affinity: "-43",
        oxidation_states: "1, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "933",
        boiling_point: "2792",
        density: "2.7",
        group_block: "metal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "BFA6A6",
        period: "3",
        group: "13",
    },
    Element {
        atomic_number: "14",
        symbol: "Si",
        name: "Silicon",
        atomic_mass: "28.0855(3)",
        electronic_configuration: "[Ne] 3s2 3p2",
        electronegativity: "1.9",
        atomic_radius: "111",
        ion_radius: "40 (+4)",
        van_der_waals_radius: "210",
        ionization_energy: "787",
        electron_affinity: "-134",
        oxidation_states: "-4, -3, -2, -1, 1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1687",
        boiling_point: "3173",
        density: "2.33",
        group_block: "metalloid",
        year_discovered: "1854",
        block: "p",
        cpk_hex_color: "F0C8A0",
        period: "3",
        group: "14",
    },
    Element {
        atomic_number: "15",
        symbol: "P",
        name: "Phosphorus",
        atomic_mass: "30.973762(2)",
        electronic_configuration: "[Ne] 3s2 3p3",
        electronegativity: "2.19",
        atomic_radius: "106",
        ion_radius: "44 (+3)",
        van_der_waals_radius: "180",
        ionization_energy: "1012",
        electron_affinity: "-72",
        oxidation_states: "-3, -2, -1, 1, 2, 3, 4, 5",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "317",
        boiling_point: "554",
        density: "1.823",
        group_block: "nonmetal",
        year_discovered: "1669",
        block: "p",
        cpk_hex_color: "FF8000",
        period: "3",
        group: "15",
    },
    Element {
        atomic_number: "16",
        symbol: "S",
        name: "Sulfur",
        atomic_mass: "32.065(5)",
        electronic_configuration: "[Ne] 3s2 3p4",
        electronegativity: "2.58",
        atomic_radius: "102",
        ion_radius: "184 (-2)",
        van_der_waals_radius: "180",
        ionization_energy: "1000",
        electron_affinity: "-200",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "388",
        boiling_point: "718",
        density: "1.96",
        group_block: "nonmetal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "FFFF30",
        period: "3",
        group: "16",
    },
    Element {
        atomic_number: "17",
        symbol: "Cl",
        name: "Chlorine",
        atomic_mass: "35.453(2)",
        electronic_configuration: "[Ne] 3s2 3p5",
        electronegativity: "3.16",
        atomic_radius: "99",
        ion_radius: "181 (-1)",
        van_der_waals_radius: "175",
        ionization_energy: "1251",
        electron_affinity: "-349",
        oxidation_states: "-1, 1, 2, 3, 4, 5, 6, 7",
        standard_state: "gas",
        bonding_type: "covalent network",
        melting_point: "172",
        boiling_point: "239",
        density: "0.003214",
        group_block: "halogen",
        year_discovered: "1774",
        block: "p",
        cpk_hex_color: "1FF01F",
        period: "3",
        group: "17",
    },
    Element {
        atomic_number: "18",
        symbol: "Ar",
        name: "Argon",
        atomic_mass: "39.948(1)",
        electronic_configuration: "[Ne] 3s2 3p6",
        electronegativity: "unknown",
        atomic_radius: "97",
        ion_radius: "unknown",
        van_der_waals_radius: "188",
        ionization_energy: "1521",
        electron_affinity: "0",
        oxidation_states: "unknown",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "84",
        boiling_point: "87",
        density: "0.001784",
        group_block: "noble gas",
        year_discovered: "1894",
        block: "p",
        cpk_hex_color: "80D1E3",
        period: "3",
        group: "18",
    },
    Element {
        atomic_number: "19",
        symbol: "K",
        name: "Potassium",
        atomic_mass: "39.0983(1)",
        electronic_configuration: "[Ar] 4s1",
        electronegativity: "0.82",
        atomic_radius: "196",
        ion_radius: "138 (+1)",
        van_der_waals_radius: "275",
        ionization_energy: "419",
        electron_affinity: "-48",
        oxidation_states: "1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "337",
        boiling_point: "1032",
        density: "0.856",
        group_block: "alkali metal",
        year_discovered: "1807",
        block: "s",
        cpk_hex_color: "8F40D4",
        period: "4",
        group: "1",
    },
    Element {
        atomic_number: "20",
        symbol: "Ca",
        name: "Calcium",
        atomic_mass: "40.078(4)",
        electronic_configuration: "[Ar] 4s2",
        electronegativity: "1",
        atomic_radius: "174",
        ion_radius: "100 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "590",
        electron_affinity: "-2",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1115",
        boiling_point: "1757",
        density: "1.55",
        group_block: "alkaline earth metal",
        year_discovered: "Ancient",
        block: "s",
        cpk_hex_color: "3DFF00",
        period: "4",
        group: "2",
    },
    Element {
        atomic_number: "21",
        symbol: "Sc",
        name: "Scandium",
        atomic_mass: "44.955912(6)",
        electronic_configuration: "[Ar] 3d1 4s2",
        electronegativity: "1.36",
        atomic_radius: "144",
        ion_radius: "74.5 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "633",
        electron_affinity: "-18",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1814",
        boiling_point: "3103",
        density: "2.985",
        group_block: "transition metal",
        year_discovered: "1876",
        block: "d",
        cpk_hex_color: "E6E6E6",
        period: "4",
        group: "3",
    },
    Element {
        atomic_number: "22",
        symbol: "Ti",
        name: "Titanium",
        atomic_mass: "47.867(1)",
        electronic_configuration: "[Ar] 3d2 4s2",
        electronegativity: "1.54",
        atomic_radius: "136",
        ion_radius: "86 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "659",
        electron_affinity: "-8",
        oxidation_states: "-1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1941",
        boiling_point: "3560",
        density: "4.507",
        group_block: "transition metal",
        year_discovered: "1791",
        block: "d",
        cpk_hex_color: "BFC2C7",
        period: "4",
        group: "4",
    },
    Element {
        atomic_number: "23",
        symbol: "V",
        name: "Vanadium",
        atomic_mass: "50.9415(1)",
        electronic_configuration: "[Ar] 3d3 4s2",
        electronegativity: "1.63",
        atomic_radius: "125",
        ion_radius: "79 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "651",
        electron_affinity: "-51",
        oxidation_states: "-1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2183",
        boiling_point: "3680",
        density: "6.11",
        group_block: "transition metal",
        year_discovered: "1803",
        block: "d",
        cpk_hex_color: "A6A6AB",
        period: "4",
        group: "5",
    },
    Element {
        atomic_number: "24",
        symbol: "Cr",
        name: "Chromium",
        atomic_mass: "51.9961(6)",
        electronic_configuration: "[Ar] 3d5 4s1",
        electronegativity: "1.66",
        atomic_radius: "127",
        ion_radius: "80 (+2*)",
        van_der_waals_radius: "unknown",
        ionization_energy: "653",
        electron_affinity: "-64",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2180",
        boiling_point: "2944",
        density: "7.14",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "8A99C7",
        period: "4",
        group: "6",
    },
    Element {
        atomic_number: "25",
        symbol: "Mn",
        name: "Manganese",
        atomic_mass: "54.938045(5)",
        electronic_configuration: "[Ar] 3d5 4s2",
        electronegativity: "1.55",
        atomic_radius: "139",
        ion_radius: "67 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "717",
        electron_affinity: "0",
        oxidation_states: "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1519",
        boiling_point: "2334",
        density: "7.47",
        group_block: "transition metal",
        year_discovered: "1774",
        block: "d",
        cpk_hex_color: "9C7AC7",
        period: "4",
        group: "7",
    },
    Element {
        atomic_number: "26",
        symbol: "Fe",
        name: "Iron",
        atomic_mass: "55.845(2)",
        electronic_configuration: "[Ar] 3d6 4s2",
        electronegativity: "1.83",
        atomic_radius: "125",
        ion_radius: "78 (+2*)",
        van_der_waals_radius: "unknown",
        ionization_energy: "763",
        electron_affinity: "-16",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1811",
        boiling_point: "3134",
        density: "7.874",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "E06633",
        period: "4",
        group: "8",
    },
    Element {
        atomic_number: "27",
        symbol: "Co",
        name: "Cobalt",
        atomic_mass: "58.933195(5)",
        electronic_configuration: "[Ar] 3d7 4s2",
        electronegativity: "1.88",
        atomic_radius: "126",
        ion_radius: "74.5 (+2*)",
        van_der_waals_radius: "unknown",
        ionization_energy: "760",
        electron_affinity: "-64",
        oxidation_states: "-1, 1, 2, 3, 4, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1768",
        boiling_point: "3200",
        density: "8.9",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "F090A0",
        period: "4",
        group: "9",
    },
    Element {
        atomic_number: "28",
        symbol: "Ni",
        name: "Nickel",
        atomic_mass: "58.6934(4)",
        electronic_configuration: "[Ar] 3d8 4s2",
        electronegativity: "1.91",
        atomic_radius: "121",
        ion_radius: "69 (+2)",
        van_der_waals_radius: "163",
        ionization_energy: "737",
        electron_affinity: "-112",
        oxidation_states: "-1, 1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1728",
        boiling_point: "3186",
        density: "8.908",
        group_block: "transition metal",
        year_discovered: "1751",
        block: "d",
        cpk_hex_color: "50D050",
        period: "4",
        group: "10",
    },
    Element {
        atomic_number: "29",
        symbol: "Cu",
        name: "Copper",
        atomic_mass: "63.546(3)",
        electronic_configuration: "[Ar] 3d10 4s1",
        electronegativity: "1.9",
        atomic_radius: "138",
        ion_radius: "77 (+1)",
        van_der_waals_radius: "140",
        ionization_energy: "746",
        electron_affinity: "-118",
        oxidation_states: "1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1358",
        boiling_point: "3200",
        density: "8.92",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "C88033",
        period: "4",
        group: "11",
    },
    Element {
        atomic_number: "30",
        symbol: "Zn",
        name: "Zinc",
        atomic_mass: "65.38(2)",
        electronic_configuration: "[Ar] 3d10 4s2",
        electronegativity: "1.65",
        atomic_radius: "131",
        ion_radius: "74 (+2)",
        van_der_waals_radius: "139",
        ionization_energy: "906",
        electron_affinity: "0",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "693",
        boiling_point: "1180",
        density: "7.14",
        group_block: "transition metal",
        year_discovered: "1746",
        block: "d",
        cpk_hex_color: "7D80B0",
        period: "4",
        group: "12",
    },
    Element {
        atomic_number: "31",
        symbol: "Ga",
        name: "Gallium",
        atomic_mass: "69.723(1)",
        electronic_configuration: "[Ar] 3d10 4s2 4p1",
        electronegativity: "1.81",
        atomic_radius: "126",
        ion_radius: "62 (+3)",
        van_der_waals_radius: "187",
        ionization_energy: "579",
        electron_affinity: "-29",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "303",
        boiling_point: "2477",
        density: "5.904",
        group_block: "metal",
        year_discovered: "1875",
        block: "p",
        cpk_hex_color: "C28F8F",
        period: "4",
        group: "13",
    },
    Element {
        atomic_number: "32",
        symbol: "Ge",
        name: "Germanium",
        atomic_mass: "72.64(1)",
        electronic_configuration: "[Ar] 3d10 4s2 4p2",
        electronegativity: "2.01",
        atomic_radius: "122",
        ion_radius: "73 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "762",
        electron_affinity: "-119",
        oxidation_states: "-4, 1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1211",
        boiling_point: "3093",
        density: "5.323",
        group_block: "metalloid",
        year_discovered: "1886",
        block: "p",
        cpk_hex_color: "668F8F",
        period: "4",
        group: "14",
    },
    Element {
        atomic_number: "33",
        symbol: "As",
        name: "Arsenic",
        atomic_mass: "74.92160(2)",
        electronic_configuration: "[Ar] 3d10 4s2 4p3",
        electronegativity: "2.18",
        atomic_radius: "119",
        ion_radius: "58 (+3)",
        van_der_waals_radius: "185",
        ionization_energy: "947",
        electron_affinity: "-78",
        oxidation_states: "-3, 2, 3, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1090",
        boiling_point: "887",
        density: "5.727",
        group_block: "metalloid",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "BD80E3",
        period: "4",
        group: "15",
    },
    Element {
        atomic_number: "34",
        symbol: "Se",
        name: "Selenium",
        atomic_mass: "78.96(3)",
        electronic_configuration: "[Ar] 3d10 4s2 4p4",
        electronegativity: "2.55",
        atomic_radius: "116",
        ion_radius: "198 (-2)",
        van_der_waals_radius: "190",
        ionization_energy: "941",
        electron_affinity: "-195",
        oxidation_states: "-2, 2, 4, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "494",
        boiling_point: "958",
        density: "4.819",
        group_block: "nonmetal",
        year_discovered: "1817",
        block: "p",
        cpk_hex_color: "FFA100",
        period: "4",
        group: "16",
    },
    Element {
        atomic_number: "35",
        symbol: "Br",
        name: "Bromine",
        atomic_mass: "79.904(1)",
        electronic_configuration: "[Ar] 3d10 4s2 4p5",
        electronegativity: "2.96",
        atomic_radius: "114",
        ion_radius: "196 (-1)",
        van_der_waals_radius: "185",
        ionization_energy: "1140",
        electron_affinity: "-325",
        oxidation_states: "-1, 1, 3, 4, 5, 7",
        standard_state: "liquid",
        bonding_type: "covalent network",
        melting_point: "266",
        boiling_point: "332",
        density: "3.12",
        group_block: "halogen",
        year_discovered: "1826",
        block: "p",
        cpk_hex_color: "A62929",
        period: "4",
        group: "17",
    },
    Element {
        atomic_number: "36",
        symbol: "Kr",
        name: "Krypton",
        atomic_mass: "83.798(2)",
        electronic_configuration: "[Ar] 3d10 4s2 4p6",
        electronegativity: "unknown",
        atomic_radius: "110",
        ion_radius: "unknown",
        van_der_waals_radius: "202",
        ionization_energy: "1351",
        electron_affinity: "0",
        oxidation_states: "2",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "116",
        boiling_point: "120",
        density: "0.00375",
        group_block: "noble gas",
        year_discovered: "1898",
        block: "p",
        cpk_hex_color: "5CB8D1",
        period: "4",
        group: "18",
    },
    Element {
        atomic_number: "37",
        symbol: "Rb",
        name: "Rubidium",
        atomic_mass: "85.4678(3)",
        electronic_configuration: "[Kr] 5s1",
        electronegativity: "0.82",
        atomic_radius: "211",
        ion_radius: "152 (+1)",
        van_der_waals_radius: "unknown",
        ionization_energy: "403",
        electron_affinity: "-47",
        oxidation_states: "1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "312",
        boiling_point: "961",
        density: "1.532",
        group_block: "alkali metal",
        year_discovered: "1861",
        block: "s",
        cpk_hex_color: "702EB0",
        period: "5",
        group: "1",
    },
    Element {
        atomic_number: "38",
        symbol: "Sr",
        name: "Strontium",
        atomic_mass: "87.62(1)",
        electronic_configuration: "[Kr] 5s2",
        electronegativity: "0.95",
        atomic_radius: "192",
        ion_radius: "118 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "550",
        electron_affinity: "-5",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1050",
        boiling_point: "1655",
        density: "2.63",
        group_block: "alkaline earth metal",
        year_discovered: "1790",
        block: "s",
        cpk_hex_color: "00FF00",
        period: "5",
        group: "2",
    },
    Element {
        atomic_number: "39",
        symbol: "Y",
        name: "Yttrium",
        atomic_mass: "88.90585(2)",
        electronic_configuration: "[Kr] 4d1 5s2",
        electronegativity: "1.22",
        atomic_radius: "162",
        ion_radius: "90 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "600",
        electron_affinity: "-30",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1799",
        boiling_point: "3618",
        density: "4.472",
        group_block: "transition metal",
        year_discovered: "1794",
        block: "d",
        cpk_hex_color: "94FFFF",
        period: "5",
        group: "3",
    },
    Element {
        atomic_number: "40",
        symbol: "Zr",
        name: "Zirconium",
        atomic_mass: "91.224(2)",
        electronic_configuration: "[Kr] 4d2 5s2",
        electronegativity: "1.33",
        atomic_radius: "148",
        ion_radius: "72 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "640",
        electron_affinity: "-41",
        oxidation_states: "1, 2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2128",
        boiling_point: "4682",
        density: "6.511",
        group_block: "transition metal",
        year_discovered: "1789",
        block: "d",
        cpk_hex_color: "94E0E0",
        period: "5",
        group: "4",
    },
    Element {
        atomic_number: "41",
        symbol: "Nb",
        name: "Niobium",
        atomic_mass: "92.90638(2)",
        electronic_configuration: "[Kr] 4d4 5s1",
        electronegativity: "1.6",
        atomic_radius: "137",
        ion_radius: "72 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "652",
        electron_affinity: "-86",
        oxidation_states: "-1, 2, 3, 4, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2750",
        boiling_point: "5017",
        density: "8.57",
        group_block: "transition metal",
        year_discovered: "1801",
        block: "d",
        cpk_hex_color: "73C2C9",
        period: "5",
        group: "5",
    },
    Element {
        atomic_number: "42",
        symbol: "Mo",
        name: "Molybdenum",
        atomic_mass: "95.96(2)",
        electronic_configuration: "[Kr] 4d5 5s1",
        electronegativity: "2.16",
        atomic_radius: "145",
        ion_radius: "69 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "684",
        electron_affinity: "-72",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2896",
        boiling_point: "4912",
        density: "10.28",
        group_block: "transition metal",
        year_discovered: "1778",
        block: "d",
        cpk_hex_color: "54B5B5",
        period: "5",
        group: "6",
    },
    Element {
        atomic_number: "43",
        symbol: "Tc",
        name: "Technetium",
        atomic_mass: "98",
        electronic_configuration: "[Kr] 4d5 5s2",
        electronegativity: "1.9",
        atomic_radius: "156",
        ion_radius: "64.5 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "702",
        electron_affinity: "-53",
        oxidation_states: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2430",
        boiling_point: "4538",
        density: "11.5",
        group_block: "transition metal",
        year_discovered: "1937",
        block: "d",
        cpk_hex_color: "3B9E9E",
        period: "5",
        group: "7",
    },
    Element {
        atomic_number: "44",
        symbol: "Ru",
        name: "Ruthenium",
        atomic_mass: "101.07(2)",
        electronic_configuration: "[Kr] 4d7 5s1",
        electronegativity: "2.2",
        atomic_radius: "126",
        ion_radius: "68 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "710",
        electron_affinity: "-101",
        oxidation_states: "-2, 1, 2, 3, 4, 5, 6, 7, 8",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2607",
        boiling_point: "4423",
        density: "12.37",
        group_block: "transition metal",
        year_discovered: "1827",
        block: "d",
        cpk_hex_color: "248F8F",
        period: "5",
        group: "8",
    },
    Element {
        atomic_number: "45",
        symbol: "Rh",
        name: "Rhodium",
        atomic_mass: "102.90550(2)",
        electronic_configuration: "[Kr] 4d8 5s1",
        electronegativity: "2.28",
        atomic_radius: "135",
        ion_radius: "66.5 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "720",
        electron_affinity: "-110",
        oxidation_states: "-1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2237",
        boiling_point: "3968",
        density: "12.45",
        group_block: "transition metal",
        year_discovered: "1803",
        block: "d",
        cpk_hex_color: "0A7D8C",
        period: "5",
        group: "9",
    },
    Element {
        atomic_number: "46",
        symbol: "Pd",
        name: "Palladium",
        atomic_mass: "106.42(1)",
        electronic_configuration: "[Kr] 4d10",
        electronegativity: "2.2",
        atomic_radius: "131",
        ion_radius: "59 (+1)",
        van_der_waals_radius: "163",
        ionization_energy: "804",
        electron_affinity: "-54",
        oxidation_states: "2, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1828",
        boiling_point: "3236",
        density: "12.023",
        group_block: "transition metal",
        year_discovered: "1803",
        block: "d",
        cpk_hex_color: "6985",
        period: "5",
        group: "10",
    },
    Element {
        atomic_number: "47",
        symbol: "Ag",
        name: "Silver",
        atomic_mass: "107.8682(2)",
        electronic_configuration: "[Kr] 4d10 5s1",
        electronegativity: "1.93",
        atomic_radius: "153",
        ion_radius: "115 (+1)",
        van_der_waals_radius: "172",
        ionization_energy: "731",
        electron_affinity: "-126",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1235",
        boiling_point: "2435",
        density: "10.49",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "C0C0C0",
        period: "5",
        group: "11",
    },
    Element {
        atomic_number: "48",
        symbol: "Cd",
        name: "Cadmium",
        atomic_mass: "112.411(8)",
        electronic_configuration: "[Kr] 4d10 5s2",
        electronegativity: "1.69",
        atomic_radius: "148",
        ion_radius: "95 (+2)",
        van_der_waals_radius: "158",
        ionization_energy: "868",
        electron_affinity: "0",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "594",
        boiling_point: "1040",
        density: "8.65",
        group_block: "transition metal",
        year_discovered: "1817",
        block: "d",
        cpk_hex_color: "FFD98F",
        period: "5",
        group: "12",
    },
    Element {
        atomic_number: "49",
        symbol: "In",
        name: "Indium",
        atomic_mass: "114.818(3)",
        electronic_configuration: "[Kr] 4d10 5s2 5p1",
        electronegativity: "1.78",
        atomic_radius: "144",
        ion_radius: "80 (+3)",
        van_der_waals_radius: "193",
        ionization_energy: "558",
        electron_affinity: "-29",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "430",
        boiling_point: "2345",
        density: "7.31",
        group_block: "metal",
        year_discovered: "1863",
        block: "p",
        cpk_hex_color: "A67573",
        period: "5",
        group: "13",
    },
    Element {
        atomic_number: "50",
        symbol: "Sn",
        name: "Tin",
        atomic_mass: "118.710(7)",
        electronic_configuration: "[Kr] 4d10 5s2 5p2",
        electronegativity: "1.96",
        atomic_radius: "141",
        ion_radius: "112 (+2)",
        van_der_waals_radius: "217",
        ionization_energy: "709",
        electron_affinity: "-107",
        oxidation_states: "-4, 2, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "505",
        boiling_point: "2875",
        density: "7.31",
        group_block: "metal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "668080",
        period: "5",
        group: "14",
    },
    Element {
        atomic_number: "51",
        symbol: "Sb",
        name: "Antimony",
        atomic_mass: "121.760(1)",
        electronic_configuration: "[Kr] 4d10 5s2 5p3",
        electronegativity: "2.05",
        atomic_radius: "138",
        ion_radius: "76 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "834",
        electron_affinity: "-103",
        oxidation_states: "-3, 3, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "904",
        boiling_point: "1860",
        density: "6.697",
        group_block: "metalloid",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "9E63B5",
        period: "5",
        group: "15",
    },
    Element {
        atomic_number: "52",
        symbol: "Te",
        name: "Tellurium",
        atomic_mass: "127.60(3)",
        electronic_configuration: "[Kr] 4d10 5s2 5p4",
        electronegativity: "2.1",
        atomic_radius: "135",
        ion_radius: "221 (-2)",
        van_der_waals_radius: "206",
        ionization_energy: "869",
        electron_affinity: "-190",
        oxidation_states: "-2, 2, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "723",
        boiling_point: "1261",
        density: "6.24",
        group_block: "metalloid",
        year_discovered: "1782",
        block: "p",
        cpk_hex_color: "D47A00",
        period: "5",
        group: "16",
    },
    Element {
        atomic_number: "53",
        symbol: "I",
        name: "Iodine",
        atomic_mass: "126.90447(3)",
        electronic_configuration: "[Kr] 4d10 5s2 5p5",
        electronegativity: "2.66",
        atomic_radius: "133",
        ion_radius: "220 (-1)",
        van_der_waals_radius: "198",
        ionization_energy: "1008",
        electron_affinity: "-295",
        oxidation_states: "-1, 1, 3, 5, 7",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "387",
        boiling_point: "457",
        density: "4.94",
        group_block: "halogen",
        year_discovered: "1811",
        block: "p",
        cpk_hex_color: "940094",
        period: "5",
        group: "17",
    },
    Element {
        atomic_number: "54",
        symbol: "Xe",
        name: "Xenon",
        atomic_mass: "131.293(6)",
        electronic_configuration: "[Kr] 4d10 5s2 5p6",
        electronegativity: "unknown",
        atomic_radius: "130",
        ion_radius: "48 (+8)",
        van_der_waals_radius: "216",
        ionization_energy: "1170",
        electron_affinity: "0",
        oxidation_states: "2, 4, 6, 8",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "161",
        boiling_point: "165",
        density: "0.0059",
        group_block: "noble gas",
        year_discovered: "1898",
        block: "p",
        cpk_hex_color: "429EB0",
        period: "5",
        group: "18",
    },
    Element {
        atomic_number: "55",
        symbol: "Cs",
        name: "Cesium",
        atomic_mass: "132.9054519(2)",
        electronic_configuration: "[Xe] 6s1",
        electronegativity: "0.79",
        atomic_radius: "225",
        ion_radius: "167 (+1)",
        van_der_waals_radius: "unknown",
        ionization_energy: "376",
        electron_affinity: "-46",
        oxidation_states: "1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "302",
        boiling_point: "944",
        density: "1.879",
        group_block: "alkali metal",
        year_discovered: "1860",
        block: "s",
        cpk_hex_color: "57178F",
        period: "6",
        group: "1",
    },
    Element {
        atomic_number: "56",
        symbol: "Ba",
        name: "Barium",
        atomic_mass: "137.327(7)",
        electronic_configuration: "[Xe] 6s2",
        electronegativity: "0.89",
        atomic_radius: "198",
        ion_radius: "135 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "503",
        electron_affinity: "-14",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1000",
        boiling_point: "2143",
        density: "3.51",
        group_block: "alkaline earth metal",
        year_discovered: "1808",
        block: "s",
        cpk_hex_color: "00C900",
        period: "6",
        group: "2",
    },
    Element {
        atomic_number: "57",
        symbol: "La",
        name: "Lanthanum",
        atomic_mass: "138.90547(7)",
        electronic_configuration: "[Xe] 5d1 6s2",
        electronegativity: "1.1",
        atomic_radius: "169",
        ion_radius: "103.2 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "538",
        electron_affinity: "-48",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1193",
        boiling_point: "3737",
        density: "6.146",
        group_block: "lanthanoid",
        year_discovered: "1839",
        block: "f",
        cpk_hex_color: "70D4FF",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "58",
        symbol: "Ce",
        name: "Cerium",
        atomic_mass: "140.116(1)",
        electronic_configuration: "[Xe] 4f1 5d1 6s2",
        electronegativity: "1.12",
        atomic_radius: "unknown",
        ion_radius: "102 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "534",
        electron_affinity: "-50",
        oxidation_states: "2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1071",
        boiling_point: "3633",
        density: "6.689",
        group_block: "lanthanoid",
        year_discovered: "1803",
        block: "f",
        cpk_hex_color: "FFFFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "59",
        symbol: "Pr",
        name: "Praseodymium",
        atomic_mass: "140.90765(2)",
        electronic_configuration: "[Xe] 4f3 6s2",
        electronegativity: "1.13",
        atomic_radius: "unknown",
        ion_radius: "99 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "527",
        electron_affinity: "-50",
        oxidation_states: "2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1204",
        boiling_point: "3563",
        density: "6.64",
        group_block: "lanthanoid",
        year_discovered: "1885",
        block: "f",
        cpk_hex_color: "D9FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "60",
        symbol: "Nd",
        name: "Neodymium",
        atomic_mass: "144.242(3)",
        electronic_configuration: "[Xe] 4f4 6s2",
        electronegativity: "1.14",
        atomic_radius: "unknown",
        ion_radius: "129 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "533",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1294",
        boiling_point: "3373",
        density: "7.01",
        group_block: "lanthanoid",
        year_discovered: "1885",
        block: "f",
        cpk_hex_color: "C7FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "61",
        symbol: "Pm",
        name: "Promethium",
        atomic_mass: "145",
        electronic_configuration: "[Xe] 4f5 6s2",
        electronegativity: "1.13",
        atomic_radius: "unknown",
        ion_radius: "97 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "540",
        electron_affinity: "-50",
        oxidation_states: "3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1373",
        boiling_point: "3273",
        density: "7.264",
        group_block: "lanthanoid",
        year_discovered: "1947",
        block: "f",
        cpk_hex_color: "A3FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "62",
        symbol: "Sm",
        name: "Samarium",
        atomic_mass: "150.36(2)",
        electronic_configuration: "[Xe] 4f6 6s2",
        electronegativity: "1.17",
        atomic_radius: "unknown",
        ion_radius: "122 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "545",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1345",
        boiling_point: "2076",
        density: "7.353",
        group_block: "lanthanoid",
        year_discovered: "1853",
        block: "f",
        cpk_hex_color: "8FFFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "63",
        symbol: "Eu",
        name: "Europium",
        atomic_mass: "151.964(1)",
        electronic_configuration: "[Xe] 4f7 6s2",
        electronegativity: "1.2",
        atomic_radius: "unknown",
        ion_radius: "117 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "547",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1095",
        boiling_point: "1800",
        density: "5.244",
        group_block: "lanthanoid",
        year_discovered: "1901",
        block: "f",
        cpk_hex_color: "61FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "64",
        symbol: "Gd",
        name: "Gadolinium",
        atomic_mass: "157.25(3)",
        electronic_configuration: "[Xe] 4f7 5d1 6s2",
        electronegativity: "1.2",
        atomic_radius: "unknown",
        ion_radius: "93.8 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "593",
        electron_affinity: "-50",
        oxidation_states: "1, 2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1586",
        boiling_point: "3523",
        density: "7.901",
        group_block: "lanthanoid",
        year_discovered: "1880",
        block: "f",
        cpk_hex_color: "45FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "65",
        symbol: "Tb",
        name: "Terbium",
        atomic_mass: "158.92535(2)",
        electronic_configuration: "[Xe] 4f9 6s2",
        electronegativity: "1.2",
        atomic_radius: "unknown",
        ion_radius: "92.3 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "566",
        electron_affinity: "-50",
        oxidation_states: "1, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1629",
        boiling_point: "3503",
        density: "8.219",
        group_block: "lanthanoid",
        year_discovered: "1843",
        block: "f",
        cpk_hex_color: "30FFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "66",
        symbol: "Dy",
        name: "Dysprosium",
        atomic_mass: "162.500(1)",
        electronic_configuration: "[Xe] 4f10 6s2",
        electronegativity: "1.22",
        atomic_radius: "unknown",
        ion_radius: "107 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "573",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1685",
        boiling_point: "2840",
        density: "8.551",
        group_block: "lanthanoid",
        year_discovered: "1886",
        block: "f",
        cpk_hex_color: "1FFFC7",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "67",
        symbol: "Ho",
        name: "Holmium",
        atomic_mass: "164.93032(2)",
        electronic_configuration: "[Xe] 4f11 6s2",
        electronegativity: "1.23",
        atomic_radius: "unknown",
        ion_radius: "90.1 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "581",
        electron_affinity: "-50",
        oxidation_states: "3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1747",
        boiling_point: "2973",
        density: "8.795",
        group_block: "lanthanoid",
        year_discovered: "1878",
        block: "f",
        cpk_hex_color: "00FF9C",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "68",
        symbol: "Er",
        name: "Erbium",
        atomic_mass: "167.259(3)",
        electronic_configuration: "[Xe] 4f12 6s2",
        electronegativity: "1.24",
        atomic_radius: "unknown",
        ion_radius: "89 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "589",
        electron_affinity: "-50",
        oxidation_states: "3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1770",
        boiling_point: "3141",
        density: "9.066",
        group_block: "lanthanoid",
        year_discovered: "1842",
        block: "f",
        cpk_hex_color: "0",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "69",
        symbol: "Tm",
        name: "Thulium",
        atomic_mass: "168.93421(2)",
        electronic_configuration: "[Xe] 4f13 6s2",
        electronegativity: "1.25",
        atomic_radius: "unknown",
        ion_radius: "103 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "597",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1818",
        boiling_point: "2223",
        density: "9.321",
        group_block: "lanthanoid",
        year_discovered: "1879",
        block: "f",
        cpk_hex_color: "00D452",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "70",
        symbol: "Yb",
        name: "Ytterbium",
        atomic_mass: "173.054(5)",
        electronic_configuration: "[Xe] 4f14 6s2",
        electronegativity: "1.1",
        atomic_radius: "unknown",
        ion_radius: "102 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "603",
        electron_affinity: "-50",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1092",
        boiling_point: "1469",
        density: "6.57",
        group_block: "lanthanoid",
        year_discovered: "1878",
        block: "f",
        cpk_hex_color: "00BF38",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "71",
        symbol: "Lu",
        name: "Lutetium",
        atomic_mass: "174.9668(1)",
        electronic_configuration: "[Xe] 4f14 5d1 6s2",
        electronegativity: "1.27",
        atomic_radius: "160",
        ion_radius: "86.1 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "524",
        electron_affinity: "-50",
        oxidation_states: "3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1936",
        boiling_point: "3675",
        density: "9.841",
        group_block: "lanthanoid",
        year_discovered: "1907",
        block: "d",
        cpk_hex_color: "00AB24",
        period: "6",
        group: "3",
    },
    Element {
        atomic_number: "72",
        symbol: "Hf",
        name: "Hafnium",
        atomic_mass: "178.49(2)",
        electronic_configuration: "[Xe] 4f14 5d2 6s2",
        electronegativity: "1.3",
        atomic_radius: "150",
        ion_radius: "71 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "659",
        electron_affinity: "0",
        oxidation_states: "2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2506",
        boiling_point: "4876",
        density: "13.31",
        group_block: "transition metal",
        year_discovered: "1923",
        block: "d",
        cpk_hex_color: "4DC2FF",
        period: "6",
        group: "4",
    },
    Element {
        atomic_number: "73",
        symbol: "Ta",
        name: "Tantalum",
        atomic_mass: "180.94788(2)",
        electronic_configuration: "[Xe] 4f14 5d3 6s2",
        electronegativity: "1.5",
        atomic_radius: "138",
        ion_radius: "72 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "761",
        electron_affinity: "-31",
        oxidation_states: "-1, 2, 3, 4, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "3290",
        boiling_point: "5731",
        density: "16.65",
        group_block: "transition metal",
        year_discovered: "1802",
        block: "d",
        cpk_hex_color: "4DA6FF",
        period: "6",
        group: "5",
    },
    Element {
        atomic_number: "74",
        symbol: "W",
        name: "Tungsten",
        atomic_mass: "183.84(1)",
        electronic_configuration: "[Xe] 4f14 5d4 6s2",
        electronegativity: "2.36",
        atomic_radius: "146",
        ion_radius: "66 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "770",
        electron_affinity: "-79",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "3695",
        boiling_point: "5828",
        density: "19.25",
        group_block: "transition metal",
        year_discovered: "1783",
        block: "d",
        cpk_hex_color: "2194D6",
        period: "6",
        group: "6",
    },
    Element {
        atomic_number: "75",
        symbol: "Re",
        name: "Rhenium",
        atomic_mass: "186.207(1)",
        electronic_configuration: "[Xe] 4f14 5d5 6s2",
        electronegativity: "1.9",
        atomic_radius: "159",
        ion_radius: "63 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "760",
        electron_affinity: "-15",
        oxidation_states: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "3459",
        boiling_point: "5869",
        density: "21.02",
        group_block: "transition metal",
        year_discovered: "1925",
        block: "d",
        cpk_hex_color: "267DAB",
        period: "6",
        group: "7",
    },
    Element {
        atomic_number: "76",
        symbol: "Os",
        name: "Osmium",
        atomic_mass: "190.23(3)",
        electronic_configuration: "[Xe] 4f14 5d6 6s2",
        electronegativity: "2.2",
        atomic_radius: "128",
        ion_radius: "63 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "840",
        electron_affinity: "-106",
        oxidation_states: "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "3306",
        boiling_point: "5285",
        density: "22.61",
        group_block: "transition metal",
        year_discovered: "1803",
        block: "d",
        cpk_hex_color: "266696",
        period: "6",
        group: "8",
    },
    Element {
        atomic_number: "77",
        symbol: "Ir",
        name: "Iridium",
        atomic_mass: "192.217(3)",
        electronic_configuration: "[Xe] 4f14 5d7 6s2",
        electronegativity: "2.2",
        atomic_radius: "137",
        ion_radius: "68 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "880",
        electron_affinity: "-151",
        oxidation_states: "-3, -1, 1, 2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2739",
        boiling_point: "4701",
        density: "22.65",
        group_block: "transition metal",
        year_discovered: "1803",
        block: "d",
        cpk_hex_color: "175487",
        period: "6",
        group: "9",
    },
    Element {
        atomic_number: "78",
        symbol: "Pt",
        name: "Platinum",
        atomic_mass: "195.084(9)",
        electronic_configuration: "[Xe] 4f14 5d9 6s1",
        electronegativity: "2.28",
        atomic_radius: "128",
        ion_radius: "86 (+2)",
        van_der_waals_radius: "175",
        ionization_energy: "870",
        electron_affinity: "-205",
        oxidation_states: "2, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2041",
        boiling_point: "4098",
        density: "21.09",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "D0D0E0",
        period: "6",
        group: "10",
    },
    Element {
        atomic_number: "79",
        symbol: "Au",
        name: "Gold",
        atomic_mass: "196.966569(4)",
        electronic_configuration: "[Xe] 4f14 5d10 6s1",
        electronegativity: "2.54",
        atomic_radius: "144",
        ion_radius: "137 (+1)",
        van_der_waals_radius: "166",
        ionization_energy: "890",
        electron_affinity: "-223",
        oxidation_states: "-1, 1, 2, 3, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1337",
        boiling_point: "3129",
        density: "19.3",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "FFD123",
        period: "6",
        group: "11",
    },
    Element {
        atomic_number: "80",
        symbol: "Hg",
        name: "Mercury",
        atomic_mass: "200.59(2)",
        electronic_configuration: "[Xe] 4f14 5d10 6s2",
        electronegativity: "2",
        atomic_radius: "149",
        ion_radius: "119 (+1)",
        van_der_waals_radius: "155",
        ionization_energy: "1007",
        electron_affinity: "0",
        oxidation_states: "1, 2, 4",
        standard_state: "liquid",
        bonding_type: "metallic",
        melting_point: "234",
        boiling_point: "630",
        density: "13.534",
        group_block: "transition metal",
        year_discovered: "Ancient",
        block: "d",
        cpk_hex_color: "B8B8D0",
        period: "6",
        group: "12",
    },
    Element {
        atomic_number: "81",
        symbol: "Tl",
        name: "Thallium",
        atomic_mass: "204.3833(2)",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p1",
        electronegativity: "2.04",
        atomic_radius: "148",
        ion_radius: "150 (+1)",
        van_der_waals_radius: "196",
        ionization_energy: "589",
        electron_affinity: "-19",
        oxidation_states: "1, 3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "577",
        boiling_point: "1746",
        density: "11.85",
        group_block: "metal",
        year_discovered: "1861",
        block: "p",
        cpk_hex_color: "A6544D",
        period: "6",
        group: "13",
    },
    Element {
        atomic_number: "82",
        symbol: "Pb",
        name: "Lead",
        atomic_mass: "207.2(1)",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p2",
        electronegativity: "2.33",
        atomic_radius: "147",
        ion_radius: "119 (+2)",
        van_der_waals_radius: "202",
        ionization_energy: "716",
        electron_affinity: "-35",
        oxidation_states: "-4, 2, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "601",
        boiling_point: "2022",
        density: "11.34",
        group_block: "metal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "575961",
        period: "6",
        group: "14",
    },
    Element {
        atomic_number: "83",
        symbol: "Bi",
        name: "Bismuth",
        atomic_mass: "208.98040(1)",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p3",
        electronegativity: "2.02",
        atomic_radius: "146",
        ion_radius: "103 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "703",
        electron_affinity: "-91",
        oxidation_states: "-3, 3, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "544",
        boiling_point: "1837",
        density: "9.78",
        group_block: "metal",
        year_discovered: "Ancient",
        block: "p",
        cpk_hex_color: "9E4FB5",
        period: "6",
        group: "15",
    },
    Element {
        atomic_number: "84",
        symbol: "Po",
        name: "Polonium",
        atomic_mass: "209",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p4",
        electronegativity: "2",
        atomic_radius: "unknown",
        ion_radius: "94 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "812",
        electron_affinity: "-183",
        oxidation_states: "-2, 2, 4, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "527",
        boiling_point: "1235",
        density: "9.196",
        group_block: "metalloid",
        year_discovered: "1898",
        block: "p",
        cpk_hex_color: "AB5C00",
        period: "6",
        group: "16",
    },
    Element {
        atomic_number: "85",
        symbol: "At",
        name: "Astatine",
        atomic_mass: "210",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p5",
        electronegativity: "2.2",
        atomic_radius: "unknown",
        ion_radius: "62 (+7)",
        van_der_waals_radius: "unknown",
        ionization_energy: "920",
        electron_affinity: "-270",
        oxidation_states: "-1, 1, 3, 5",
        standard_state: "solid",
        bonding_type: "covalent network",
        melting_point: "575",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "halogen",
        year_discovered: "1940",
        block: "p",
        cpk_hex_color: "754F45",
        period: "6",
        group: "17",
    },
    Element {
        atomic_number: "86",
        symbol: "Rn",
        name: "Radon",
        atomic_mass: "222",
        electronic_configuration: "[Xe] 4f14 5d10 6s2 6p6",
        electronegativity: "unknown",
        atomic_radius: "145",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "1037",
        electron_affinity: "unknown",
        oxidation_states: "2",
        standard_state: "gas",
        bonding_type: "atomic",
        melting_point: "202",
        boiling_point: "211",
        density: "0.00973",
        group_block: "noble gas",
        year_discovered: "1900",
        block: "p",
        cpk_hex_color: "428296",
        period: "6",
        group: "18",
    },
    Element {
        atomic_number: "87",
        symbol: "Fr",
        name: "Francium",
        atomic_mass: "223",
        electronic_configuration: "[Rn] 7s1",
        electronegativity: "0.7",
        atomic_radius: "unknown",
        ion_radius: "180 (+1)",
        van_der_waals_radius: "unknown",
        ionization_energy: "380",
        electron_affinity: "unknown",
        oxidation_states: "1",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "alkali metal",
        year_discovered: "1939",
        block: "s",
        cpk_hex_color: "420066",
        period: "7",
        group: "1",
    },
    Element {
        atomic_number: "88",
        symbol: "Ra",
        name: "Radium",
        atomic_mass: "226",
        electronic_configuration: "[Rn] 7s2",
        electronegativity: "0.9",
        atomic_radius: "unknown",
        ion_radius: "148 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "509",
        electron_affinity: "unknown",
        oxidation_states: "2",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "973",
        boiling_point: "2010",
        density: "5",
        group_block: "alkaline earth metal",
        year_discovered: "1898",
        block: "s",
        cpk_hex_color: "007D00",
        period: "7",
        group: "2",
    },
    Element {
        atomic_number: "89",
        symbol: "Ac",
        name: "Actinium",
        atomic_mass: "227",
        electronic_configuration: "[Rn] 6d1 7s2",
        electronegativity: "1.1",
        atomic_radius: "unknown",
        ion_radius: "112 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "499",
        electron_affinity: "unknown",
        oxidation_states: "3",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1323",
        boiling_point: "3473",
        density: "10.07",
        group_block: "actinoid",
        year_discovered: "1899",
        block: "f",
        cpk_hex_color: "70ABFA",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "90",
        symbol: "Th",
        name: "Thorium",
        atomic_mass: "232.03806(2)",
        electronic_configuration: "[Rn] 6d2 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "94 (+4)",
        van_der_waals_radius: "unknown",
        ionization_energy: "587",
        electron_affinity: "unknown",
        oxidation_states: "2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "2023",
        boiling_point: "5093",
        density: "11.724",
        group_block: "actinoid",
        year_discovered: "1828",
        block: "f",
        cpk_hex_color: "00BAFF",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "91",
        symbol: "Pa",
        name: "Protactinium",
        atomic_mass: "231.03588(2)",
        electronic_configuration: "[Rn] 5f2 6d1 7s2",
        electronegativity: "1.5",
        atomic_radius: "unknown",
        ion_radius: "104 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "568",
        electron_affinity: "unknown",
        oxidation_states: "3, 4, 5",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1845",
        boiling_point: "4273",
        density: "15.37",
        group_block: "actinoid",
        year_discovered: "1913",
        block: "f",
        cpk_hex_color: "00A1FF",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "92",
        symbol: "U",
        name: "Uranium",
        atomic_mass: "238.02891(3)",
        electronic_configuration: "[Rn] 5f3 6d1 7s2",
        electronegativity: "1.38",
        atomic_radius: "unknown",
        ion_radius: "102.5 (+3)",
        van_der_waals_radius: "186",
        ionization_energy: "598",
        electron_affinity: "unknown",
        oxidation_states: "3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1408",
        boiling_point: "4200",
        density: "19.05",
        group_block: "actinoid",
        year_discovered: "1789",
        block: "f",
        cpk_hex_color: "008FFF",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "93",
        symbol: "Np",
        name: "Neptunium",
        atomic_mass: "237",
        electronic_configuration: "[Rn] 5f4 6d1 7s2",
        electronegativity: "1.36",
        atomic_radius: "unknown",
        ion_radius: "110 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "605",
        electron_affinity: "unknown",
        oxidation_states: "3, 4, 5, 6, 7",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "917",
        boiling_point: "4273",
        density: "20.45",
        group_block: "actinoid",
        year_discovered: "1940",
        block: "f",
        cpk_hex_color: "0080FF",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "94",
        symbol: "Pu",
        name: "Plutonium",
        atomic_mass: "244",
        electronic_configuration: "[Rn] 5f6 7s2",
        electronegativity: "1.28",
        atomic_radius: "unknown",
        ion_radius: "100 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "585",
        electron_affinity: "unknown",
        oxidation_states: "3, 4, 5, 6, 7",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "913",
        boiling_point: "3503",
        density: "19.816",
        group_block: "actinoid",
        year_discovered: "1940",
        block: "f",
        cpk_hex_color: "006BFF",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "95",
        symbol: "Am",
        name: "Americium",
        atomic_mass: "243",
        electronic_configuration: "[Rn] 5f7 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "126 (+2)",
        van_der_waals_radius: "unknown",
        ionization_energy: "578",
        electron_affinity: "unknown",
        oxidation_states: "2, 3, 4, 5, 6",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1449",
        boiling_point: "2284",
        density: "unknown",
        group_block: "actinoid",
        year_discovered: "1944",
        block: "f",
        cpk_hex_color: "545CF2",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "96",
        symbol: "Cm",
        name: "Curium",
        atomic_mass: "247",
        electronic_configuration: "[Rn] 5f7 6d1 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "97 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "581",
        electron_affinity: "unknown",
        oxidation_states: "3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1618",
        boiling_point: "3383",
        density: "13.51",
        group_block: "actinoid",
        year_discovered: "1944",
        block: "f",
        cpk_hex_color: "785CE3",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "97",
        symbol: "Bk",
        name: "Berkelium",
        atomic_mass: "247",
        electronic_configuration: "[Rn] 5f9 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "96 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "601",
        electron_affinity: "unknown",
        oxidation_states: "3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1323",
        boiling_point: "unknown",
        density: "14.78",
        group_block: "actinoid",
        year_discovered: "1949",
        block: "f",
        cpk_hex_color: "8A4FE3",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "98",
        symbol: "Cf",
        name: "Californium",
        atomic_mass: "251",
        electronic_configuration: "[Rn] 5f10 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "95 (+3)",
        van_der_waals_radius: "unknown",
        ionization_energy: "608",
        electron_affinity: "unknown",
        oxidation_states: "2, 3, 4",
        standard_state: "solid",
        bonding_type: "metallic",
        melting_point: "1173",
        boiling_point: "unknown",
        density: "15.1",
        group_block: "actinoid",
        year_discovered: "1950",
        block: "f",
        cpk_hex_color: "A136D4",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "99",
        symbol: "Es",
        name: "Einsteinium",
        atomic_mass: "252",
        electronic_configuration: "[Rn] 5f11 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "619",
        electron_affinity: "unknown",
        oxidation_states: "2, 3",
        standard_state: "solid",
        bonding_type: "unknown",
        melting_point: "1133",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "actinoid",
        year_discovered: "1952",
        block: "f",
        cpk_hex_color: "B31FD4",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "100",
        symbol: "Fm",
        name: "Fermium",
        atomic_mass: "257",
        electronic_configuration: "[Rn] 5f12 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "627",
        electron_affinity: "unknown",
        oxidation_states: "2, 3",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "1800",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "actinoid",
        year_discovered: "1952",
        block: "f",
        cpk_hex_color: "B31FBA",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "101",
        symbol: "Md",
        name: "Mendelevium",
        atomic_mass: "258",
        electronic_configuration: "[Rn] 5f13 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "635",
        electron_affinity: "unknown",
        oxidation_states: "2, 3",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "1100",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "actinoid",
        year_discovered: "1955",
        block: "f",
        cpk_hex_color: "B30DA6",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "102",
        symbol: "No",
        name: "Nobelium",
        atomic_mass: "259",
        electronic_configuration: "[Rn] 5f14 7s2",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "642",
        electron_affinity: "unknown",
        oxidation_states: "2, 3",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "1100",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "actinoid",
        year_discovered: "1957",
        block: "f",
        cpk_hex_color: "BD0D87",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "103",
        symbol: "Lr",
        name: "Lawrencium",
        atomic_mass: "262",
        electronic_configuration: "[Rn] 5f14 7s2 7p1",
        electronegativity: "1.3",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "3",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "1900",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1961",
        block: "d",
        cpk_hex_color: "C70066",
        period: "7",
        group: "3",
    },
    Element {
        atomic_number: "104",
        symbol: "Rf",
        name: "Rutherfordium",
        atomic_mass: "267",
        electronic_configuration: "[Rn] 5f14 6d2 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "4",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1969",
        block: "d",
        cpk_hex_color: "CC0059",
        period: "7",
        group: "4",
    },
    Element {
        atomic_number: "105",
        symbol: "Db",
        name: "Dubnium",
        atomic_mass: "268",
        electronic_configuration: "[Rn] 5f14 6d3 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1967",
        block: "d",
        cpk_hex_color: "D1004F",
        period: "7",
        group: "5",
    },
    Element {
        atomic_number: "106",
        symbol: "Sg",
        name: "Seaborgium",
        atomic_mass: "271",
        electronic_configuration: "[Rn] 5f14 6d4 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1974",
        block: "d",
        cpk_hex_color: "D90045",
        period: "7",
        group: "6",
    },
    Element {
        atomic_number: "107",
        symbol: "Bh",
        name: "Bohrium",
        atomic_mass: "272",
        electronic_configuration: "[Rn] 5f14 6d5 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1976",
        block: "d",
        cpk_hex_color: "E00038",
        period: "7",
        group: "7",
    },
    Element {
        atomic_number: "108",
        symbol: "Hs",
        name: "Hassium",
        atomic_mass: "270",
        electronic_configuration: "[Rn] 5f14 6d6 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1984",
        block: "d",
        cpk_hex_color: "E6002E",
        period: "7",
        group: "8",
    },
    Element {
        atomic_number: "109",
        symbol: "Mt",
        name: "Meitnerium",
        atomic_mass: "276",
        electronic_configuration: "[Rn] 5f14 6d7 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1982",
        block: "d",
        cpk_hex_color: "EB0026",
        period: "7",
        group: "9",
    },
    Element {
        atomic_number: "110",
        symbol: "Ds",
        name: "Darmstadtium",
        atomic_mass: "281",
        electronic_configuration: "[Rn] 5f14 6d9 7s1",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1994",
        block: "d",
        cpk_hex_color: "unknown",
        period: "7",
        group: "10",
    },
    Element {
        atomic_number: "111",
        symbol: "Rg",
        name: "Roentgenium",
        atomic_mass: "280",
        electronic_configuration: "[Rn] 5f14 6d10 7s1",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1994",
        block: "d",
        cpk_hex_color: "unknown",
        period: "7",
        group: "11",
    },
    Element {
        atomic_number: "112",
        symbol: "Cn",
        name: "Copernicium",
        atomic_mass: "285",
        electronic_configuration: "[Rn] 5f14 6d10 7s2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "transition metal",
        year_discovered: "1996",
        block: "d",
        cpk_hex_color: "unknown",
        period: "7",
        group: "12",
    },
    Element {
        atomic_number: "113",
        symbol: "Nh",
        name: "Nihonium",
        atomic_mass: "284",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p1",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "post-transition metal",
        year_discovered: "2003",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "13",
    },
    Element {
        atomic_number: "114",
        symbol: "Fl",
        name: "Flerovium",
        atomic_mass: "289",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p2",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "post-transition metal",
        year_discovered: "1998",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "14",
    },
    Element {
        atomic_number: "115",
        symbol: "Mc",
        name: "Moscovium",
        atomic_mass: "288",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p3",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "post-transition metal",
        year_discovered: "2003",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "15",
    },
    Element {
        atomic_number: "116",
        symbol: "Lv",
        name: "Livermorium",
        atomic_mass: "293",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p4",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "post-transition metal",
        year_discovered: "2000",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "16",
    },
    Element {
        atomic_number: "117",
        symbol: "Ts",
        name: "Tennessine",
        atomic_mass: "294",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p5",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "post-transition metal",
        year_discovered: "2010",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "17",
    },
    Element {
        atomic_number: "118",
        symbol: "Og",
        name: "Oganesson",
        atomic_mass: "294",
        electronic_configuration: "[Rn] 5f14 6d10 7s2 7p6",
        electronegativity: "unknown",
        atomic_radius: "unknown",
        ion_radius: "unknown",
        van_der_waals_radius: "unknown",
        ionization_energy: "unknown",
        electron_affinity: "unknown",
        oxidation_states: "unknown",
        standard_state: "unknown",
        bonding_type: "unknown",
        melting_point: "unknown",
        boiling_point: "unknown",
        density: "unknown",
        group_block: "noble gas",
        year_discovered: "2002",
        block: "p",
        cpk_hex_color: "unknown",
        period: "7",
        group: "18",
    },
];
